### Recuperar todo
GET https://examen-cuenta.onrender.com/cuenta

### Recuperar un dato por numeroCuenta
GET https://examen-cuenta.onrender.com/cuenta/1


### Crear un dato con POST
POST https://examen-cuenta.onrender.com/cuenta
Content-Type: application/json

{
  "documentoCliente": "100",
  "claveAcceso": "12345"
}

### Borrar un dato
DELETE https://examen-cuenta.onrender.com/cuenta/1

### Retiro
PATCH https://examen-cuenta.onrender.com/cuenta/1
Content-Type: application/json

{
  "retiro": 20000
}

### Deposito
PATCH https://examen-cuenta.onrender.com/cuenta/1
Content-Type: application/json

{
  "deposito": 20000
}